### ISSUE TITLE
Client gives up on reconnect

### ISSUE THREAD

**Issue by joshforbes** [ably/ably-go#606] opened 2023-06-28 16:36 UTC
Hello!

We're in the long overdue process of getting ably-go updated to the most recent version. As we're testing the new implementation we noticed a device that has become disconnected from Ably. Here is the last message:

<img width="691" alt="image" src="https://github.com/ably/ably-go/assets/3682518/e56d77b3-311e-4348-be56-71087bca307e">

```
ably connection state changed: current: DISCONNECTED; previous: CONNECTED; event: DISCONNECTED; retry in: 0s; error reason: [ErrorInfo :Post "[https://rest.ably.io:443/keys/MpxHNQ.2JQwTQ/requestToken](https://rest.ably.io/keys/MpxHNQ.2JQwTQ/requestToken)": context deadline exceeded (Client.Timeout exceeded while awaiting headers) code=80003 disconnected statusCode=0] See https://help.ably.io/error/80003
```

Per the docs, the is should have recovered on its own but it did not:

<img width="668" alt="image" src="https://github.com/ably/ably-go/assets/3682518/ef6b11ce-b8f5-4a6c-8016-8e6cee72d0a6">

Is there anything special we should be doing to make sure this recovers?

**Comment by sacOO7** [comment] 2023-06-28 16:44
Okay, I had some questions before this issue is resolved
1. ably-go version
2. go version
3. Which type of auth mechanism are you using?
4. Is this only happening with the latest version of `ably-go` or was this used to happen before? Are you sure something changed in the latest version of ably-go, that is causing this issue?
5. If you have a small working snippet that would be able to reproduce this issue, it would be super useful for us to resolve it asap!

**Comment by joshforbes** [comment] 2023-06-28 18:02
1. ably-go 1.2.12
2. Go 1.20
3. Token
4. We upgraded from ably-go 1.1.3 🫣. Things were a lot different and we had years of workarounds to problems.
5. I'm sorry but I don't. I don't think we're doing anything special with our implementation. Also, I should say that this is a rather rare problem. We're testing on 83 different devices with a token TTL set to 1 hour. After two days, one device is stuck in this state. Though once we put this "in the wild" we can't afford to lose contact with any devices.

**Comment by sacOO7** [comment] 2023-06-28 18:05
So, currently we are facing this issue with only one of the device out of 83 devices and it remains in the same `DISCONNECTED` state?

**Comment by joshforbes** [comment] 2023-06-28 18:22
That is correct. The other 82 devices (well 79 - see other HTTP/2 issue) are reconnecting as expected. This device was also reconnecting as expected until this context timeout pushed it into a bad state.

Here is the exact timestamp (EDT):
Jun 27 20:04:53

I don't know if the "keys" in the URL help pinpoint anything:

`https://rest.ably.io/keys/MpxHNQ.2JQwTQ/requestToken`

Unfortunately, I don't have any more information than this. We're going to continue monitoring the staging environment for an extended period before going to production so I will bring in any other data that I find. Is there anything else that I should be doing to make sure a reconnect after a timeout?

**Comment by sacOO7** [comment] 2023-06-28 18:27
Even if it goes into the disconnected state, ideally it should recover from it and should make reconnect attempt in 15 seconds. What is it's current behavior? does it remain in `disconnected`/`suspended` state or goes into a `failed` state? 
For `disconnected`/`suspended`, retry will happen 15s/30s respectively.

**Comment by joshforbes** [comment] 2023-06-28 18:40
We added debugging to spit out a log every time the Ably state changes. The last message we get is when it goes from `connected -> disconnected`. We have code in place to restart our agent if it ever moves to `failed` so I'm fairly certain that it isn't doing so.

**Comment by sacOO7** [comment] 2023-06-28 18:43
Then maybe somehow it's going into a locking state ... 
This information is useful. We will try to reproduce this from our side. 
It would be great if you can send us logs till this particular state is reached.

**Comment by sacOO7** [comment] 2023-06-28 18:45
@joshforbes Currently we have two open issues, so the other issue is the same as this one right? If it is, you can close that issue and we can continue our conversation here.

**Comment by joshforbes** [comment] 2023-06-28 18:50
> Then maybe somehow it's going into a locking state ...
This information is useful. We will try to reproduce this from our side.
It would be great if you can send us logs till this particular state is reached.

Does Ably have a "verbose mode" that I should turn on while we try to get this error to happen again?

**Comment by joshforbes** [comment] 2023-06-28 18:51
> @joshforbes Currently we have two open issues, so the other issue is the same as this one right? If it is, you can close that issue and we can continue our conversation here.

Sorry for the confusion. The other open issue is about a different error (HTTP/2).

**Comment by sacOO7** [comment] 2023-06-28 19:02
> > Then maybe somehow it's going into a locking state ...
> > This information is useful. We will try to reproduce this from our side.
> > It would be great if you can send us logs till this particular state is reached.
> 
> Does Ably have a "verbose mode" that I should turn on while we try to get this error to happen again?

You can pass `LogHandler` in the clientOptions -> https://github.com/ably/ably-go/blob/cbb0f591f117534172e936dfaa2cd1d9e6fb6b8c/ably/options.go#L404C2-L404C12.

**Comment by sacOO7** [comment] 2023-11-08 12:02
@joshforbes let us know if the issue still persists, if not, we can close the issue : )

**Comment by sacOO7** [comment] 2024-01-16 10:41
Closing the issue since no new user is facing this issue : )

**Closed** 2024-01-16 10:42 UTC
